name: "LrcLib"
guid: "D106EBE6-9CA8-4FBC-9CD1-A92A213DA9F9"
version: "1"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "crobibero"
overview: "Download lyrics from https://lrclib.net/"
description: >
  Download lyrics from https://lrclib.net/

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.LrcLib.dll"
changelog: |-
