name: "LrcLib"
guid: "1316cd9a-f417-4aa0-b859-2d50f764f45e"
version: "1"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "Felitendo"
overview: "Download lyrics from https://lrclib.net/"
description: >
  Download lyrics from https://lrclib.net/

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.LrcLib.dll"
changelog: |-
